VND_NOTES = [1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000, 500000]

MAX_SSP_PORT = 200
CRC_SSP_SEED = 0xFFFF
CRC_SSP_POLY = 0x8005
SSP_STX = 0x7F


SSP_CMD_SYNC = 0x11
SSP_CMD_ENABLE = 0xA
SSP_CMD_ENABLE_HIGHER_PROTOCOL = 0x19
SSP_CMD_SET_INHIBITS = 0x2
SSP_CMD_POLL = 0x7
SSP_CMD_DISABLE = 0x9
SSP_CMD_REJECT_NOTE = 0x8

SSP_RESPONSE_OK = 0xF0
SSP_RESPONSE_UNKNOWN_COMMAND = 0xF2
SSP_RESPONSE_INCORRECT_PARAMETERS = 0xF3
SSP_RESPONSE_INVALID_PARAMETER = 0xF4
SSP_RESPONSE_COMMAND_NOT_PROCESSED = 0xF5
SSP_RESPONSE_SOFTWARE_ERROR = 0xF6
SSP_RESPONSE_CHECKSUM_ERROR = 0xF7
SSP_RESPONSE_FAILURE = 0xF8
SSP_RESPONSE_HEADER_FAILURE = 0xF9
SSP_RESPONSE_KEY_NOT_SET = 0xFA
SSP_RESPONSE_TIMEOUT = 0xFF
SSP_RESPONSE_COMMAND_NOT_PROCESSED_BUSY = 0xF503

# Poll Responses
SSP_POLL_RESET = 0xF1
SSP_POLL_READ = 0xEF #next byte is channel (0 for unknown)
SSP_POLL_CREDIT = 0xEE #next byte is channel
SSP_POLL_REJECTING = 0xED
SSP_POLL_REJECTED = 0xEC
SSP_POLL_STACKING = 0xCC
SSP_POLL_STACKED = 0xEB
SSP_POLL_SAFE_JAM = 0xEA
SSP_POLL_UNSAFE_JAM = 0xE9
SSP_POLL_DISABLED = 0xE8
SSP_POLL_FRAUD_ATTEMPT = 0xE6 #next byte is channel
SSP_POLL_STACKER_FULL = 0xE7
SSP_POLL_CLEARED_FROM_FRONT = 0xE1
SSP_POLL_CLEARED_INTO_CASHBOX = 0xE2
SSP_POLL_BARCODE_VALIDATE = 0xE5
SSP_POLL_BARCODE_ACK = 0xD1
SSP_POLL_CASH_BOX_REMOVED = 0xE3
SSP_POLL_CASH_BOX_REPLACED = 0xE4
SSP_POLL_DISPENSING = 0xDA
SSP_POLL_DISPENSED = 0xD2
SSP_POLL_JAMMED = 0xD5
SSP_POLL_HALTED = 0xD6
SSP_POLL_FLOATING = 0xD7
SSP_POLL_FLOATED = 0xD8
SSP_POLL_TIMEOUT = 0xD9
SSP_POLL_INCOMPLETE_PAYOUT = 0xDC
SSP_POLL_INCOMPLETE_FLOAT = 0xDD
SSP_POLL_CASHBOX_PAID = 0xDE
SSP_POLL_COIN_CREDIT = 0xDF
SSP_POLL_EMPTYING = 0xC2
SSP_POLL_EMPTY = 0xC3
SSP_POLL_COINS_LOW = 0xD3
SSP_POLL_COINS_EMPTY = 0xD4
