import requests

def post(url, json, retry=3):
    retries = 0

    while True:
        if retries > retry: break
        try:
            response = requests.post(url, verify=False, json=json)
            if response.status_code == 200: return response
        except: pass
        retries+=1

    return None

def remove_sign(string):
    string=string.replace('á', 'a')
    string=string.replace('à', 'a')
    string=string.replace('ạ', 'a')
    string=string.replace('ả', 'a')
    string=string.replace('ã', 'a')
    string=string.replace('â', 'a')
    string=string.replace('ấ', 'a')
    string=string.replace('ầ', 'a')
    string=string.replace('ậ', 'a')
    string=string.replace('ẩ', 'a')
    string=string.replace('ẫ', 'a')
    string=string.replace('ă', 'a')
    string=string.replace('ắ', 'a')
    string=string.replace('ằ', 'a')
    string=string.replace('ặ', 'a')
    string=string.replace('ẳ', 'a')
    string=string.replace('ẵ', 'a')

    string=string.replace('Á', 'A')
    string=string.replace('À', 'A')
    string=string.replace('Ạ', 'A')
    string=string.replace('Ả', 'A')
    string=string.replace('Ã', 'A')
    string=string.replace('Â', 'A')
    string=string.replace('Ấ', 'A')
    string=string.replace('Ầ', 'A')
    string=string.replace('Ậ', 'A')
    string=string.replace('Ẩ', 'A')
    string=string.replace('Ẫ', 'A')
    string=string.replace('Ă', 'A')
    string=string.replace('Ắ', 'A')
    string=string.replace('Ằ', 'A')
    string=string.replace('Ặ', 'A')
    string=string.replace('Ẳ', 'A')
    string=string.replace('Ẵ', 'A')

    string=string.replace('é', 'e')
    string=string.replace('è', 'e')
    string=string.replace('ẹ', 'e')
    string=string.replace('ẻ', 'e')
    string=string.replace('ẽ', 'e')
    string=string.replace('ê', 'e')
    string=string.replace('ế', 'e')
    string=string.replace('ề', 'e')
    string=string.replace('ệ', 'e')
    string=string.replace('ể', 'e')
    string=string.replace('é', 'e')
    string=string.replace('ễ', 'e')

    string=string.replace('É', 'E')
    string=string.replace('È', 'E')
    string=string.replace('Ẹ', 'E')
    string=string.replace('Ẻ', 'E')
    string=string.replace('Ẽ', 'E')
    string=string.replace('Ê', 'E')
    string=string.replace('Ế', 'E')
    string=string.replace('Ề', 'E')
    string=string.replace('Ệ', 'E')
    string=string.replace('Ể', 'E')
    string=string.replace('É', 'E')
    string=string.replace('Ễ', 'E')

    string=string.replace('ó', 'o')
    string=string.replace('ò', 'o')
    string=string.replace('ọ', 'o')
    string=string.replace('ỏ', 'o')
    string=string.replace('õ', 'o')
    string=string.replace('ô', 'o')
    string=string.replace('ố', 'o')
    string=string.replace('ồ', 'o')
    string=string.replace('ộ', 'o')
    string=string.replace('ổ', 'o')
    string=string.replace('ỗ', 'o')
    string=string.replace('ơ', 'o')
    string=string.replace('ớ', 'o')
    string=string.replace('ờ', 'o')
    string=string.replace('ợ', 'o')
    string=string.replace('ở', 'o')
    string=string.replace('ỡ', 'o')

    string=string.replace('Ó', 'O')
    string=string.replace('Ò', 'O')
    string=string.replace('Ọ', 'O')
    string=string.replace('Ỏ', 'O')
    string=string.replace('Õ', 'O')
    string=string.replace('Ô', 'O')
    string=string.replace('Ố', 'O')
    string=string.replace('Ồ', 'O')
    string=string.replace('Ộ', 'O')
    string=string.replace('Ổ', 'O')
    string=string.replace('Ỗ', 'O')
    string=string.replace('Ơ', 'O')
    string=string.replace('Ớ', 'O')
    string=string.replace('Ờ', 'O')
    string=string.replace('Ợ', 'O')
    string=string.replace('Ở', 'O')
    string=string.replace('Ỡ', 'O')

    string=string.replace('ú', 'u')
    string=string.replace('ù', 'u')
    string=string.replace('ụ', 'u')
    string=string.replace('ủ', 'u')
    string=string.replace('ũ', 'u')
    string=string.replace('ư', 'u')
    string=string.replace('ứ', 'u')
    string=string.replace('ừ', 'u')
    string=string.replace('ự', 'u')
    string=string.replace('ử', 'u')
    string=string.replace('ữ', 'u')

    string=string.replace('Ú', 'U')
    string=string.replace('Ù', 'U')
    string=string.replace('Ụ', 'U')
    string=string.replace('Ủ', 'U')
    string=string.replace('Ũ', 'U')
    string=string.replace('Ư', 'U')
    string=string.replace('Ứ', 'U')
    string=string.replace('Ừ', 'U')
    string=string.replace('Ự', 'U')
    string=string.replace('Ử', 'U')
    string=string.replace('Ữ', 'U')

    string=string.replace('í', 'i')
    string=string.replace('ì', 'i')
    string=string.replace('ị', 'i')
    string=string.replace('ỉ', 'i')
    string=string.replace('ĩ', 'i')

    string=string.replace('Í', 'I')
    string=string.replace('Ì', 'I')
    string=string.replace('Ị', 'I')
    string=string.replace('Ỉ', 'I')
    string=string.replace('Ĩ', 'I')

    string=string.replace('đ', 'd')
    string=string.replace('Đ', 'D')

    string=string.replace('ý', 'y')
    string=string.replace('ỳ', 'y')
    string=string.replace('ỵ', 'y')
    string=string.replace('ỷ', 'y')
    string=string.replace('ỹ', 'y')

    string=string.replace('Ý', 'Y')
    string=string.replace('Ỳ', 'Y')
    string=string.replace('Ỵ', 'Y')
    string=string.replace('Ỷ', 'Y')
    string=string.replace('Ỹ', 'Y')

    return string